when:
  event: push
  branch: [main, master]

steps:
  build-and-push:
    image: gcr.io/kaniko-project/executor:latest
    commands:
      - /kaniko/executor
        --context=.
        --destination=ghcr.io/zaakirio/verbski-web:latest
        --cache=true
        --cache-repo=ghcr.io/zaakirio/cache
        --cache-ttl=72h
    resources:
      requests:
        memory: 256Mi
        cpu: 200m
      limits:
        memory: 1Gi
        cpu: 1
    backend_options:
      kubernetes:
        volumes:
          - name: docker-config
            mount_path: /kaniko/.docker
            secret:
              secret_name: ghcr-push-secret
              items:
                - key: .dockerconfigjson
                  path: config.json
