when:
  event: push
  branch:
    - main
    - master

steps:
  build-and-push:
    image: gcr.io/kaniko-project/executor:latest-debug
    commands:
      - mkdir -p /kaniko/.docker
      - echo "$DOCKER_CONFIG_JSON" > /kaniko/.docker/config.json
      - /kaniko/executor
        --context=.
        --destination=ghcr.io/zaakirio/verbski-web:latest
        --cache=true
        --cache-repo=ghcr.io/zaakirio/cache
        --cache-ttl=72h
    secrets:
      - docker_config_json
    resources:
      requests:
        memory: 256Mi
        cpu: 200m
      limits:
        memory: 1Gi
        cpu: 1
