when:
  event: push
  branch:
    - main
    - master

steps:
  build-and-push:
    image: docker:28
    environment:
      DOCKER_CONFIG_JSON:
        from_secret: docker_config_json
    commands:
      - mkdir -p /root/.docker
      - echo "$DOCKER_CONFIG_JSON" > /root/.docker/config.json
      - docker build -t ghcr.io/zaakirio/verbski-web:latest .
      - docker push ghcr.io/zaakirio/verbski-web:latest
